version: '3.8'

services:
  backend:
    build:
      context: ./bio-check-api
    ports:
      - "5000:5000"
    volumes:
      - ./bio-check-api:/app:delegated
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  frontend:
    build:
      context: ./bio-check-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: